server {
    listen 80;
    server_name _;
    absolute_redirect off;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    gzip on;
    gzip_types text/css application/javascript;

    location = /healthz {
        default_type text/plain;
        return 200 "ok\n";
    }

    location = / {
        return 302 /sem-valor/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
